import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import mars from "../public/marsAvatarLg.png"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael A Ramos Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Developed By Mike</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li>
                <a className=' bg-gradient-to-r from-green-700 to-green-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
              </li>
              
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className=' text-5xl py-2 text-green-700 font-medium'>Michael A Ramos</h2>
            <h3 className=' text-2xl py-2'>Full Stack Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Coding coder who likes to code!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16'>
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='flex items-center mx-auto bg-gradient-to-b from-green-700 rounded-full w-80 h-80 mt-20'>
            <div className='mb-20'>
            <Image src={mars} />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 mt-5'>Something something</h3>
            <p className='text-md py-2 leading-8 text-gray-800'> looking for a yab</p>
            <p className='text-md py-2 leading-8 text-gray-800'>I know how to code</p>
          </div>
          <div>

          </div>
        </section>
        
      </main>
    </>
  )
}
